sudo: required
services:
  - docker

before_install:
  - docker build -t elanvital80/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run elanvital80/react-test npm test -- --coverage

after_success:
  - docker build -t elanvital80/multi-client ./client
  - docker build -t elanvital80/multi-nginx ./nginx
  - docker build -t elanvital80/multi-server ./server
  - docker build -t elanvital80/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images an push them to docker hub
  - docker push elanvital80/multi-client
  - docker push elanvital80/multi-nginx
  - docker push elanvital80/multi-server
  - docker push elanvital80/multi-worker